### ISSUE TITLE
errors in MonoMac code in CoreGraphicsGraphics.cs

### ISSUE THREAD

**Issue by JoeStrout** [praeclarum/CrossGraphics#5]
I get several errors on line 379 of CoreGraphicsGraphics.cs:

CrossGraphics/src/CoreGraphicsGraphics.cs(52,52): Error CS1502: The best overloaded method match for `MonoMac.AppKit.NSImage.AsCGImage(ref System.Drawing.RectangleF, MonoMac.AppKit.NSGraphicsContext, MonoMac.Foundation.NSDictionary)' has some invalid arguments (CS1502) (ClockMac)

CrossGraphics/src/CoreGraphicsGraphics.cs(52,52): Error CS1620: Argument `#1' is missing`ref' modifier (CS1620) (ClockMac)

CrossGraphics/src/CoreGraphicsGraphics.cs(32,32): Error CS1502: The best overloaded method match for `CrossGraphics.CoreGraphics.UIKitImage.UIKitImage(MonoMac.CoreGraphics.CGImage)' has some invalid arguments (CS1502) (ClockMac)

CoreGraphicsGraphics.cs(32,32): Error CS1503: Argument `#1' cannot convert`object' expression to type `MonoMac.CoreGraphics.CGImage' (CS1503) (ClockMac)

In addition, I also get

CrossGraphics/src/CoreGraphicsGraphics.cs(22,22): Error CS0535: `CrossGraphics.CoreGraphics.CoreGraphicsGraphics' does not implement interface member`CrossGraphics.IGraphics.Clear(CrossGraphics.Color)' (CS0535) (ClockMac)

I'll see if I can figure out how to fix these, though I'm still quite new to Mono.

**Comment by praeclarum** [comment]
This has been fixed.
